language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script: pytest
deploy:
  provider: pypi
  user: capodoster
  password:
     secure: pU4pD2GTJ51xKNAUXTelO/nX6QGy/6J6OCe4UVTM6zo4iUFAOGlgyqF0FnZBqxUTEWCZGELpdllRNjl1XXRQdt67anLYDkAUS5kZdpDbYi/b6sZS1UHiXefdwGbuF7szWjSZpxDbWpuHLRBHNWhjtTpqTL2ybXpSCq3ai4fCHROxnRl/OA4JFo4YXeh47wLqdQ4D0Uio3kUEwyq67m5t4BHmZeAYvde5Ku4S/XLk25o/6ur16MBgQvnMxjWPL/tXKyrOj6yHAjraSBl8EdygxY+wXoRTI0yBS9eIuZAc3sE1W0K8I/24Us28IDizk8ebgnGOEtKRJNen5kkuvQlMM8lS3FHv35AO48HRBShph6p22ul9J0+THmMEzHKnU3B1mgp2aRcbi3H6iqgxWCDZgu4Jnqbsqj3FyWyhfK4/MAeCU9tQ52lLsZcHGtLcSgtUx9c6nHTfewLBcx8BjMzcJFiXYZCWnM2QYb2g0o4lxiSITFN9AAfUIbOS3KxLscowLVn4LiskfiXwl0VPt2cZ6+6k+5R1zzt4ywkj6mnbB1F7OmMaa3bZbClHjIx4H4XcmS0GJGj6sh1ZZ5khXS8vOJKBWhwOJonf8HFmpCmm+iGwDs8GTVvxEEPurAcI5mjtDNVdVMaQEmrajvgn7fYKIWf439bZpzLImKMj37zPf9Q=
  on:
    tags: true