language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script: pytest
deploy:
  provider: pypi
  user: capodoster
  password:
    secure: NgZo4ORR2i+580iSGLqT7GD26BKQXzXQPOB9tosVF2/SY+0IqV4wn1bI54qTrXmt6jGo/Oi2mrB00dHT00p/yfbzJ8fP3igTPFpXccvoIAl7B3a7EYRk6BwARA//SlijuGzrNyUuSv0t/am+sGFXrbNVGEo5HJ1toXonXEAJnqxG/QAIaKtY6o+gWHeLKdJWKxlho/KxQPqYnEwmRrbh9o11HlmOjUKxgbepDoT4nLl6K5lYWiRaX/aB9S71uiK2N8k+981HcfqaCsiS0jhGyq4NlCQmurgonMgzyseouYqL+OKc6z5CNB7PuCtzbimD5tm8GI2WepZ81T80yTYkneI549iQ1BNyYUDidl8r0t8i8U41d+3Hmvj3ryeSI0KkgOAnJhLBg0Bk6oBGfDwoUt8CoWLHnqSR+4rZuygI6HUZ/z+SV0g18bDsq08Vwe0g3FJeSMfXh2x5qdhIeEwjHYCFoswpiAxclkum59xR9rCrE5i0+CQqZ6n/niC8gVan0dl3IopgjHf2cGMOp3bO+O0b+Ntul3Z2vxgrMa2cRoPMKUYZ7Z+ClihhO5SRQgYaMWJda+z5zkRkLb/JlRUuDV8ntvWgUsfuDBTSenZAI7X6OTVNNs3UBfSVTlNNA1W5wAoIhnywrVSpOJa/zJpARbZ4Tu1yVUhTbJ4tPK4OosM=
  skip_cleanup: true
  on:
    tags: true
