language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script: pytest
deploy:
  provider: pypi
  user: capodoster
  password:
    secure: X2WeH3U7EitfiCe96p3jiIiYoZEXid2NGoNzmnMoNoOzRoIb7/cenwm61p/dDTAgLCOHh9U65bzdKjjMN68MoDuFUQzOJF2Zs7PQMgGq9L2hKA6Jmw1PHDVV5UqafGdLmEwGwh04k9H2NNXbxsZstrZ/vaCbMToBTSMs9Jj9i2FGJORIRHxMDusfSoUzssw3zu11O8cD5/oA6jEbubtcL94GVspik09ERFMUsYYf3rgZHZDOCu7xLicYZCL5IHHWlfEQ5dRozoFamsqn73iNmzPeOxDPzQjzAwbhtylo4jWP6GRGIm4hNU42IUUZ5kcwbNzjvQHG7nSE4sV3v31SQueQubI+tEAp3pjgO3inkd8nR6mItcWnd0eYFvJbOce6QMukt1Cs94AqajUq1Q3wsP6XVuIUPiEgulLEeWLwi2a6SUxzZ85O14q1dZ4kw8HbGqHZVMRoWCRa/ZDInvWv+kzVmAKbvfyWXfthv2a5DjSxZobA8gzmObKsvs0o8B71Umy3K69emZaxV6gwTJfe0DEu6BuU3usyXA84MNO1nQUCTDkBG4BC6gNQaogm6MKihhr+V2bjCJRTZ3z9barP24C8fRgRRs2QoaZDrcqgiuHzrfN+gsg2VoI+bl+/Yd6/zazT/Fm/oNSPpSJDYXEoq/2QLWg9FGvBgiZY+QIJTuQ=
  skip_cleanup: true
  on:
    tags: true
