language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script: pytest
deploy:
  provider: pypi
  user: capodoster
  skip_cleanup: true
  password:
    secure: UTFmUYOK4ChUuLi7QpywYMb1coUDr8dPwyMJBehgxx9DXwJRiG3kg8gCE9pT66CI31trNdHO+wiIccM3ncntANKDCcvk3C11bHqyyJsbP0C7ixhwbrNWRnbf8oHsIrVVD0B+whwV/FeBpeVCSRNLlwj/eGwsyNcHdALSm6LO7du9SqWVabQZ0G0SUlEvNEgQnb8TU39+ZdPWjfOM+XpOg/CSRESLegmaZPwasXqqUxq2G0QlcBPNJ20yzoWVjxM85a8+97X5S+Zwaw4qsjs8iOZ6ODfalogK92fAWCbEe3K8VzVz9MsppSOdvu/FfNUL1sVKLMwrq/S3oXDDedwH7YntKIdOKqfz8Lmp6Xce0UBjkZvGEhnwRP2wsU6BDkQc3pM3HQOTTqfkCOASzA/Uw3NoSMQEX0wA5wYwD+LEK5+ITWYY/ejT0tk9toPA00HvM+uk1C3BupKXuK3RQyw0LsR3WxbK+AB6LEc2VAyWeMbhTY8/l1jYLY1F1uq6A/Dc7b5GgNxcfQdmfpvPalIfRmLaTRQiADjp+4JwIcaWzuXSaW4rKFyMA0By3ft8LGfwp9/df5bJjvxtASebWSXtEdxVqVy7COSGaV9h5KMsCHs4mFS6p5Ivi84MGtlclORZJaR/SAjE3ULo9cBrzrCb3legXiVAaKq964blQQxSTwI=
  on:
    tags: true
