language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script: pytest
deploy:
  provider: pypi
  user: capodoster
  password:
    secure: Y04IebmC2pc+AE46Es9+FMZPN5hzR+gLPDZpFxLsHDgN9fS6aAxnfHT4IRm6aQKZYcrrbBWmJPxM6OT8zW+CHaUfCIaNzasOerhdXVNzRRs2+Y+yLlfoLuHoIhvwg/3SrWHQbMObGxOk32C/EZ1xeuKAnLxuHt+EbznpGITmIHHI5zHtFUwR4/BQZmpbfsMV9sJm0pb+i1/wkCwsmx8dIlwPDrRYJaCzS7xLK5L5c51g7EtvaPCzabGuQ8fI0ydZu5pDz+fyAt0/qWZOqmP9d61GK49JXHNlO5XHhMoJ2D96HLXjcuMFJIKKtc4uingVoBOLtRauVCAllTFSEIsPHcLWOR+ITziRGzT2nryBxI0i5pVQigZqcNsfkOTR9o6Cke9Lyi0edYY+00sF5k9uqd+dHInDxllY/M2iKjEoTsnuKQfuwBTCx82skzs5lRMCekuBLnythzXQ5aRFNR078RkWTxEtjlr4tZTrVLfBrhhkzLaCvVwkIBnnYCbDk7IvKzz6OnjMQc7z0EljFRwbZy03B7R8cTTxeA1D2ZKPNzGaGQqxpEn/nxjV64FEH3W6Qr2d/gk59nGz6Ns3McHJ92OEmM20mnw7xj/U5zno6Aa/PI+Odsc+cBYgIIzNU3Z2lD0d4QduSETltcd1iiF0I3b1b+R8cQRld4HzaZNdiFo=
  skip_cleanup: true
  on:
    tags: true
